spring:
  jpa:
    properties.hibernate.jdbc.lob.non_contextual_creation: trueblog
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/myDataExamples
    username: postgres
    password: root

server:
  port: 8080
